### ISSUE TITLE
Failed to instantiate [com.microsoft.azure.spring.cloud.autoconfigure.telemetry.TelemetrySender

### ISSUE THREAD

**Issue by roshinirevindranathan** [MicrosoftDocs/azure-dev-docs#128]
Not sure whether this document works... I am getting the following exception during the application startup.
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.microsoft.azure.spring.cloud.autoconfigure.telemetry.TelemetrySender]: Factory method 'telemetrySender' threw exception; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
________________

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
[main] ERROR org.springframework.boot.SpringApplication - Application run failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'telemetrySender' defined in class path resource [com/microsoft/azure/spring/cloud/autoconfigure/telemetry/TelemetryAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.microsoft.azure.spring.cloud.autoconfigure.telemetry.TelemetrySender]: Factory method 'telemetrySender' threw exception; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:656)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:636)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1338)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1177)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:557)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:517)
        at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:323)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:321)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:882)
        at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:878)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
        at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:141)
        at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:747)
        at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:397)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:315)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1226)
        at org.springframework.boot.SpringApplication.run(SpringApplication.java:1215)
        at com.example.jms.JmsApplication.main(JmsApplication.java:10)
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.microsoft.azure.spring.cloud.autoconfigure.telemetry.TelemetrySender]: Factory method 'telemetrySender' threw exception; nested exception is java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
        at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651)
        ... 19 more
Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
        at com.microsoft.applicationinsights.internal.config.JaxbAppInsightsConfigurationBuilder.build(JaxbAppInsightsConfigurationBuilder.java:47)
        at com.microsoft.applicationinsights.internal.config.TelemetryConfigurationFactory.initialize(TelemetryConfigurationFactory.java:89)
        at com.microsoft.applicationinsights.TelemetryConfiguration.getActive(TelemetryConfiguration.java:70)
        at com.microsoft.applicationinsights.TelemetryClient.&lt;init&gt;(TelemetryClient.java:83)
        at com.microsoft.azure.spring.cloud.autoconfigure.telemetry.TelemetrySender.buildTelemetryClient(TelemetrySender.java:35)
        at com.microsoft.azure.spring.cloud.autoconfigure.telemetry.TelemetrySender.&lt;init&gt;(TelemetrySender.java:29)
        at com.microsoft.azure.spring.cloud.autoconfigure.telemetry.TelemetryAutoConfiguration.telemetrySender(TelemetryAutoConfiguration.java:34)
        at com.microsoft.azure.spring.cloud.autoconfigure.telemetry.TelemetryAutoConfiguration$$EnhancerBySpringCGLIB$$dfabb774.CGLIB$telemetrySender$0(&lt;generated&gt;)
        at com.microsoft.azure.spring.cloud.autoconfigure.telemetry.TelemetryAutoConfiguration$$EnhancerBySpringCGLIB$$dfabb774$$FastClassBySpringCGLIB$$bcaff186.invoke(&lt;generated&gt;)
        at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:244)
        at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:331)
        at com.microsoft.azure.spring.cloud.autoconfigure.telemetry.TelemetryAutoConfiguration$$EnhancerBySpringCGLIB$$dfabb774.telemetrySender(&lt;generated&gt;)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:154)
        ... 20 more
Caused by: java.lang.ClassNotFoundException: javax.xml.bind.JAXBException
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
        at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
        ... 37 more

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ac19ce1b-2184-5487-67c9-22c4ff97336d
* Version Independent ID: ecc6b6cf-73e4-1575-add0-cb44d7aa4fcf
* Content: [How to use the Spring Boot Starter for Azure Storage](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-storage)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-storage.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-storage.md)
* Service: **storage**
* GitHub Login: @bmitchell287
* Microsoft Alias: **brendm**

**Comment by bmitchell287** [comment]
@seanli1988 @yucwan - Sean/Yuchen - Would you please look into this issue? Thanks.

cc: @KarlErickson

**Comment by seanli1988** [comment]
This is a spring integrations related issue. I've opened a bug tracking and assigned it to myself.

**Comment by pjirsa** [comment]
@seanli1988 and @KarlErickson any updates? my Cx is also seeing the same issue when trying the sample walkthrough on this page: https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-azure-event-hub

**Comment by jialindai** [comment]
Which version of JDK is used in customer's case?
