### ISSUE TITLE
Error when follwoing the tutorial

### ISSUE THREAD

**Issue by harry12345678910** [MicrosoftDocs/azure-dev-docs#1345]
Dear all, 

I receive an error when following the tutorial:

  az connection create mysql-flexible \
       --resource-group <your_resource_group_name> \
       --connection mysql_conn \
       --target-resource-group <your_resource_group_name> \
       --server mysqlflexibletest \
       --database demo \
       --user-account mysql-identity-id=/subscriptions/<your_subscription_id>/resourcegroups/<your_resource_group_name>/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<your_user_assigned_managed_identity_name> \
       --query authInfo.userName \
       --output tsv

The command failed with an unexpected error. Here is the traceback:
'MysqlFlexibleHandler' object has no attribute 'identity_client_id'
Traceback (most recent call last):
  File "/usr/lib64/az/lib/python3.9/site-packages/knack/cli.py", line 233, in invoke
    cmd_result = self.invocation.execute(args)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 663, in execute
    raise ex
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 726, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 697, in _run_job
    result = cmd_copy(params)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/__init__.py", line 333, in __call__
    return self.handler(*args, **kwargs)
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/core/commands/command_operation.py", line 121, in handler
    return op(**command_args)
  File "/home/harald/.azure/cliextensions/serviceconnector-passwordless/azext_serviceconnector_passwordless/custom.py", line 70, in local_connection_create_ext
    return local_connection_create_func(cmd, client,
  File "/usr/lib64/az/lib/python3.9/site-packages/azure/cli/command_modules/serviceconnector/custom.py", line 584, in local_connection_create_func
    new_auth_info = enable_mi_for_db_linker(
  File "/home/harald/.azure/cliextensions/serviceconnector-passwordless/azext_serviceconnector_passwordless/_credential_free.py", line 144, in enable_mi_for_db_linker
    target_handler.create_aad_user()
  File "/home/harald/.azure/cliextensions/serviceconnector-passwordless/azext_serviceconnector_passwordless/_credential_free.py", line 307, in create_aad_user
    query_list = self.get_create_query()
  File "/home/harald/.azure/cliextensions/serviceconnector-passwordless/azext_serviceconnector_passwordless/_credential_free.py", line 427, in get_create_query
    client_id = self.identity_client_id
AttributeError: 'MysqlFlexibleHandler' object has no attribute 'identity_client_id'

---
#### Document Details

⚠ *Do not edit this section. It is required for learn.microsoft.com ➟ GitHub issue linking.*

* ID: cd86960b-f6f5-60aa-deb5-f41a583fba80
* Version Independent ID: fd9c6cc8-0f1f-e1d8-8e2b-b9ff5c54eef2
* Content: [Use Spring Data JPA with Azure Database for MySQL - Java on Azure](https://learn.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-data-jpa-with-azure-mysql?tabs=passwordless%2Cservice-connector&pivots=mysql-passwordless-flexible-server)
* Content Source: [articles/java/spring-framework/configure-spring-data-jpa-with-azure-mysql.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-data-jpa-with-azure-mysql.md)
* Service: **mysql**
* GitHub Login: @KarlErickson
* Microsoft Alias: **bbenz**

**Comment by jdubois** [comment]
It's hard to know with so little information, but this looks like an API issue (an attribute not being present on an object), so could you give us the version of the AZ CLI you are using? Maybe you are using an outdated version, and passwordless is a rather new option, so that would make sense.

**Comment by KarlErickson** [comment]
No reply, so I'm closing. @harry12345678910 if this is still an issue for you when using the latest version of the Azure CLI, then please submit your feedback again and provide as much information as you can. Thanks!
