### ISSUE TITLE
Mention how to configure general Python app

### ISSUE THREAD

**Issue by cdeil** [MicrosoftDocs/azure-dev-docs#142]
At https://docs.microsoft.com/en-us/azure/developer/python/tutorial-deploy-app-service-on-linux-04 you explain how to configure startup for Django and Flask.

In my case I'd e.g. like to run FastAPI.

Could you please add an example how to start any WSGI or ASGI app, maybe using FastAPI as an example?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: ca484d54-3c17-221d-f751-b3ae55e0c70d
* Version Independent ID: 5c59d1fc-a585-46c5-0cff-d474ded58c04
* Content: [Step 4: Configure a custom startup file for Python apps on Azure App Service on Linux](https://docs.microsoft.com/en-us/azure/developer/python/tutorial-deploy-app-service-on-linux-04)
* Content Source: [articles/python/tutorial-deploy-app-service-on-linux-04.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/python/tutorial-deploy-app-service-on-linux-04.md)
* Product: **azure-python**
* GitHub Login: @kraigb
* Microsoft Alias: **kraigb**

**Comment by kraigb** [comment]
I'd be happy to update the article, but I would need a little help with the details (otherwise it's going to be a low-priority item on my backlog). My experience with WSGI/ASGI matters is somewhat limited.

In general, I would expect you could launch a FastAPI or any other app with gunicorn using the same $(MODULE_NAME):$(VARIABLE_NAME) format as shown for Flask. According to https://docs.gunicorn.org/en/stable/run.html, "The module name can be a full dotted path. The variable name refers to a WSGI callable that should be found in the specified module."

Would that not be the case? I would expect that starting a FastAPI app or something using another framework is going to look similar to what the article shows for Flask. In that case, perhaps all that the article needs here is to generalize the Flask section and mention the bit from the gunicorn docs?

**Comment by cdeil** [comment]
@kraigb  - Thanks for the quick reply!

I'm also new to web development and deployment, so I probably won't be very helpful.

> In that case, perhaps all that the article needs here is to generalize the Flask section and mention the bit from the gunicorn docs?

Yes, I think what that is correct. Basically in Python thanks to WSGI one can run most Python web apps in the same way, never mind the framework (Flask, FastAPI, ...).

E.g. note how the equivalent thing is explained here:
* https://devcenter.heroku.com/articles/getting-started-with-python?singlepage=true#define-a-procfile 
* https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/python-configuration-procfile.html

Just now I also found this which has a lot of infos, maybe you could link to there.
* https://docs.microsoft.com/en-us/azure/app-service/containers/how-to-configure-python#container-startup-process

But even after that it's still not really clear to me how to me how I can set that command. Is it possible to pass the command directly to the `--startup-file` option? Or do I always have to put it in `startup.txt`?
https://docs.microsoft.com/en-us/cli/azure/webapp?view=azure-cli-latest#az-webapp-create

Here's the command that should work with fastapi:
https://fastapi.tiangolo.com/deployment/#alternatively-deploy-fastapi-without-docker

**Comment by kraigb** [comment]
Yes, you can put the command directly into the startup setting; a separate file isn't required, but is generally recommended because it can then be included in the app's source repository rather than being a bit of information that exists only in Azure.

From the links you gave (thank you!), I would think you can just refer to the appropriate module:app for most frameworks other than Django, in which case yes, generalizing this article as well as the how-to-configure-python one (which I also wrote originally), would be more inclusive. I'll put that on my backlog.

**Comment by cdeil** [comment]
Following [this](https://fastapi.tiangolo.com/deployment/#deploy-a-fastapi-application) and [this](https://www.uvicorn.org/#running-with-gunicorn) I tried this `startup.txt`
```
gunicorn --bind=0.0.0.0 application:app -w 4 -k uvicorn.workers.UvicornWorker
```
with a getting started fastapi example `application.py`
```
import logging
from fastapi import FastAPI

logging.basicConfig(level=logging.INFO)

app = FastAPI()

logging.info("test1")


@app.get("/")
def read_root():
    logging.info("test2")
    return {"Hello": "World"}


@app.get("/items/{item_id}")
def read_item(item_id: int, q: str = None):
    logging.info("test3")
    return {"item_id": item_id, "q": q}
```

Getting this error:
```
/appsvctmp/volatile/logs/runtime/02cc3a0a08b4ccc93b1321a5da88925f720cdb5ade2bd2b29b427184713845de.log 
2020-05-06T20:36:21.605028366Z: [INFO]  Using packages from virtual environment antenv located at /antenv.
2020-05-06T20:36:21.610171700Z: [INFO]  Updated PYTHONPATH to ':/antenv/lib/python3.7/site-packages'
2020-05-06T20:36:22.803184886Z: [ERROR]  [2020-05-06 20:36:22 +0000] [41] [INFO] Starting gunicorn 20.0.4
2020-05-06T20:36:22.804109792Z: [ERROR]  [2020-05-06 20:36:22 +0000] [41] [INFO] Listening at: http://0.0.0.0:8000 (41)
2020-05-06T20:36:22.804515295Z: [ERROR]  [2020-05-06 20:36:22 +0000] [41] [INFO] Using worker: sync
2020-05-06T20:36:22.814369161Z: [ERROR]  [2020-05-06 20:36:22 +0000] [44] [INFO] Booting worker with pid: 44
2020-05-06T20:36:25.148299083Z: [INFO]  172.16.1.1 - - [06/May/2020:20:36:25 +0000] "GET /robots933456.txt HTTP/1.1" 404 232 "-" "-"
2020-05-06T20:39:07.528669765Z: [INFO]  172.16.1.1 - - [06/May/2020:20:39:07 +0000] "GET / HTTP/1.1" 200 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
2020-05-06T20:40:07.675102253Z: [INFO]  172.16.1.1 - - [06/May/2020:20:40:07 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"
2020-05-06T20:40:09.174358904Z: [INFO]  172.16.1.1 - - [06/May/2020:20:40:09 +0000] "GET / HTTP/1.1" 304 0 "-" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_4) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.129 Safari/537.36"


/appsvctmp/volatile/logs/runtime/3150ab424b266685b788620ad895c0698a738343adfe3c5ede12ea168b666eb9.log 
2020-05-06T21:43:14.658206972Z: [ERROR]  [2020-05-06 21:43:14 +0000] [45] [INFO] Booting worker with pid: 45
2020-05-06T21:43:15.079905797Z: [ERROR]  INFO:root:test1
2020-05-06T21:43:15.119061959Z: [ERROR]  [2020-05-06 21:43:15 +0000] [45] [ERROR] Error handling request /robots933456.txt
2020-05-06T21:43:15.119084460Z: [ERROR]  Traceback (most recent call last):
2020-05-06T21:43:15.119089860Z: [ERROR]    File "/opt/python/3.7.5/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 134, in handle
2020-05-06T21:43:15.119100660Z: [ERROR]      self.handle_request(listener, req, client, addr)
2020-05-06T21:43:15.119104860Z: [ERROR]    File "/opt/python/3.7.5/lib/python3.7/site-packages/gunicorn/workers/sync.py", line 175, in handle_request
2020-05-06T21:43:15.119108860Z: [ERROR]      respiter = self.wsgi(environ, resp.start_response)
2020-05-06T21:43:15.119112760Z: [ERROR]  TypeError: __call__() missing 1 required positional argument: 'send'
2020-05-06T21:43:15.121617477Z: [INFO]  172.16.1.1 - - [06/May/2020:21:43:15 +0000] "GET /robots933456.txt HTTP/1.1" 500 0 "-" "-"
```

@kraigb  - if you manage to get FastAPI to run, please let me know.

**Comment by cdeil** [comment]
Found this: https://github.com/microsoft/cookiecutter-spacy-fastapi/blob/master/%7B%7Bcookiecutter.project_slug%7D%7D/main.py

Will try tomorrow.

**Comment by cdeil** [comment]
I did manage to run my FastAPI app by putting this in my `startup.sh`:
```
python -m uvicorn application:app --host 0.0.0.0
```
Looks like one can put any startup command one likes in that file, it's just executed like a bash command?

There were two gotchas for me:
1. When creating the resource, I forgot to declare `--startup-file startup.sh`, so yesterday while I was trying out things, it was never used.
2. Just putting `uvicorn` in `requirements.txt` means that it'll be installed, but for some reason it won't be on the path. So one has to put `python -m uvicorn` instead of just `uvicorn` as command in `startup.sh`.

I'm so happy it's working!

@kraigb - I think if you do find the time to adjust the tutorial, it'll be really nice for Python devs to learn that they can use any Python web app, not just Flask or Django. Especially for REST APIs, things like FlaskAPI or Django REST framework are really popular, and Azure is a nice way to deploy it, if one can make it over the initial hump to get it to run.

**Comment by kraigb** [comment]
Thanks for reporting back! I'm glad you got it working, and I appreciate the details you've found. With uvicorn, requirements are always installed in a virtual environment and aren't assumed to be executable tools like uvicorn. So python -m is exactly the right answer.

Good note about including --startup-file; that would certainly matter! And yes, you can put any command in the startup file; I think you can even put in multiple lines if needed. In whatever case, I like using the file because you can have it in source control rather than a hard-coded command in the service.

I should have time to update the article in the next week or two. Thanks again!
