### ISSUE TITLE
Azure function console log is not expected

### ISSUE THREAD

**Issue by debinaik** [MicrosoftDocs/azure-dev-docs#174]
Hi , 
I was trying to setup azure function setup in IntelliJ by following "  https://docs.microsoft.com/en-us/azure/developer/java/toolkit-for-intellij/quickstart-functions  " link. Build is successful .  

But while running the azure function i,e section ( https://docs.microsoft.com/en-us/azure/developer/java/toolkit-for-intellij/quickstart-functions#run-the-function-app-locally ) ,in IntelliJ console I am not getting expected output. It only reflects   "Func host start at port : 7071" . remaining logs are no showing .  Also I am unable to get output from the link http://localhost:7071/api/HttpTrigger-Java?name=Azure . Since all logs are not coming in IntelliJ console, I hope azure function is not starting properly. Please help me on same.

Also, I could see below warning in IntelliJ Event log.  

Exception in Azure Toolkit for IntelliJ (3.36.0-2020.1)

java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.Worker thread.
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: rx.exceptions.OnErrorFailedException: Error occurred when trying to propagate error to Observer.onError
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:187)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.onError(OperatorSubscribeOn.java:80)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:212)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:50)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 6 more
Caused by: rx.exceptions.CompositeException: 2 exceptions occurred. 
	... 16 more
Caused by: rx.exceptions.CompositeException$CompositeExceptionCausalChain: Chain of Causes for CompositeException In Order Received =>
	at rx.exceptions.CompositeException.getCause(CompositeException.java:129)
	at java.base/java.lang.Throwable.printEnclosedStackTrace(Throwable.java:711)
	at java.base/java.lang.Throwable.printEnclosedStackTrace(Throwable.java:713)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:671)
	at java.base/java.lang.Throwable.printStackTrace(Throwable.java:725)
	at org.apache.log4j.DefaultThrowableRenderer.render(DefaultThrowableRenderer.java:60)
	at com.intellij.idea.IdeaLogger.lambda$static$1(IdeaLogger.java:38)
	at org.apache.log4j.spi.ThrowableInformation.getThrowableStrRep(ThrowableInformation.java:89)
	at org.apache.log4j.spi.LoggingEvent.getThrowableStrRep(LoggingEvent.java:413)
	at org.apache.log4j.WriterAppender.subAppend(WriterAppender.java:313)
	at org.apache.log4j.RollingFileAppender.subAppend(RollingFileAppender.java:276)
	at org.apache.log4j.WriterAppender.append(WriterAppender.java:162)
	at org.apache.log4j.AppenderSkeleton.doAppend(AppenderSkeleton.java:251)
	at org.apache.log4j.helpers.AppenderAttachableImpl.appendLoopOnAppenders(AppenderAttachableImpl.java:66)
	at org.apache.log4j.Category.callAppenders(Category.java:206)
	at org.apache.log4j.Category.forcedLog(Category.java:391)
	at org.apache.log4j.Category.error(Category.java:322)
	at com.intellij.idea.IdeaLogger.error(IdeaLogger.java:104)
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:172)
	at com.intellij.ide.plugins.StartupAbortedException.processException(StartupAbortedException.java:28)
	at com.intellij.ide.plugins.MainRunner$2.uncaughtException(MainRunner.java:39)
	at rx.internal.schedulers.ScheduledAction.signalError(ScheduledAction.java:68)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:59)
	... 6 more
Caused by: java.io.IOException: Cannot run program "func" (in directory "C:\Users\80228766\IdeaProjects\azure-function-examples\target\azure-functions\azure-function-examples-1590043510133"): CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1128)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1071)
	at com.microsoft.intellij.runner.functions.localrun.FunctionRunState.runFunctionCli(FunctionRunState.java:120)
	at com.microsoft.intellij.runner.functions.localrun.FunctionRunState.executeSteps(FunctionRunState.java:112)
	at com.microsoft.intellij.runner.functions.localrun.FunctionRunState.executeSteps(FunctionRunState.java:66)
	at com.microsoft.intellij.runner.AzureRunProfileState.lambda$execute$0(AzureRunProfileState.java:70)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:48)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:33)
	at rx.Observable.unsafeSubscribe(Observable.java:10327)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.call(OperatorSubscribeOn.java:100)
	at rx.internal.schedulers.CachedThreadScheduler$EventLoopWorker$1.call(CachedThreadScheduler.java:230)
	at rx.internal.schedulers.ScheduledAction.run(ScheduledAction.java:55)
	... 6 more
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
	at java.base/java.lang.ProcessImpl.create(Native Method)
	at java.base/java.lang.ProcessImpl.<init>(ProcessImpl.java:478)
	at java.base/java.lang.ProcessImpl.start(ProcessImpl.java:154)
	at java.base/java.lang.ProcessBuilder.start(ProcessBuilder.java:1107)
	... 17 more
Caused by: java.lang.NullPointerException
	at com.microsoft.intellij.runner.functions.localrun.FunctionRunState.onFail(FunctionRunState.java:232)
	at com.microsoft.intellij.runner.AzureRunProfileState.onFail(AzureRunProfileState.java:97)
	at com.microsoft.intellij.runner.AzureRunProfileState.lambda$execute$2(AzureRunProfileState.java:86)
	at rx.internal.util.ActionSubscriber.onError(ActionSubscriber.java:44)
	at rx.observers.SafeSubscriber._onError(SafeSubscriber.java:153)
	at rx.observers.SafeSubscriber.onError(SafeSubscriber.java:115)
	at rx.internal.operators.OperatorSubscribeOn$SubscribeOnSubscriber.onError(OperatorSubscribeOn.java:80)
	at rx.exceptions.Exceptions.throwOrReport(Exceptions.java:212)
	at rx.internal.operators.OnSubscribeFromCallable.call(OnSubscribeFromCallable.java:50)
	... 11 more

Thanks

**Comment by KarlErickson** [comment]
@debinaik thanks for the feedback! We'll investigate and update the topic.

**Comment by debinaik** [comment]
@KarlErickson , did you get a chance to find the root cause ? Request your findings..

**Comment by Dahu-Search** [comment]
Hi, 
I also see exactly the same issue when following the instructions in that tutorial. The project builds, and it will run successfully from the command line by running "mvn azure-functions:run" but not when started in IntelliJ.
Any progress in finding the cause?
Thanks

**Comment by KarlErickson** [comment]
@debinaik @Dahu-Search one of our devs has replied "Thanks for your report, this is an IntelliJ issue which didn't load the Path correctly, you may refer https://github.com/microsoft/azure-tools-for-java/wiki/FAQ for more information." I hope that helps!
