### ISSUE TITLE
Following the instructions generates an Exception

### ISSUE THREAD

**Issue by jbx1** [MicrosoftDocs/azure-dev-docs#644]
Following the instructions, the following Exception occurs. Not sure why, because the topic is already in use by another Spring Boot application using the normal Kafka client. 

Seems to be caused by this error: `Caused by: java.lang.IllegalArgumentException: checkpointConnectionString can't be null or empty, check whether checkpoint-storage-account is configured in the configuration file.`

But there is no mention of checkpoint connection strings in the tutorial. 

```
org.springframework.cloud.stream.binder.BinderException: Exception thrown while starting consumer: 
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:462) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:91) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	at org.springframework.cloud.stream.binder.AbstractBinder.bindConsumer(AbstractBinder.java:143) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	at org.springframework.cloud.stream.binding.BindingService.doBindConsumer(BindingService.java:177) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	at org.springframework.cloud.stream.binding.BindingService.bindConsumer(BindingService.java:134) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	at org.springframework.cloud.stream.binding.AbstractBindableProxyFactory.createAndBindInputs(AbstractBindableProxyFactory.java:118) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.doStartWithBindable(InputBindingLifecycle.java:58) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	at java.base/java.util.LinkedHashMap$LinkedValues.forEach(LinkedHashMap.java:608) ~[na:na]
	at org.springframework.cloud.stream.binding.AbstractBindingLifecycle.start(AbstractBindingLifecycle.java:57) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	at org.springframework.cloud.stream.binding.InputBindingLifecycle.start(InputBindingLifecycle.java:34) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
	at org.springframework.context.support.DefaultLifecycleProcessor.doStart(DefaultLifecycleProcessor.java:178) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.context.support.DefaultLifecycleProcessor.access$200(DefaultLifecycleProcessor.java:54) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.context.support.DefaultLifecycleProcessor$LifecycleGroup.start(DefaultLifecycleProcessor.java:356) ~[spring-context-5.3.12.jar:5.3.12]
	at java.base/java.lang.Iterable.forEach(Iterable.java:75) ~[na:na]
	at org.springframework.context.support.DefaultLifecycleProcessor.startBeans(DefaultLifecycleProcessor.java:155) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.context.support.DefaultLifecycleProcessor.onRefresh(DefaultLifecycleProcessor.java:123) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.context.support.AbstractApplicationContext.finishRefresh(AbstractApplicationContext.java:935) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:586) ~[spring-context-5.3.12.jar:5.3.12]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:754) ~[spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:434) ~[spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:338) ~[spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1343) ~[spring-boot-2.5.6.jar:2.5.6]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1332) ~[spring-boot-2.5.6.jar:2.5.6]
      ...
Caused by: java.lang.IllegalArgumentException: checkpointConnectionString can't be null or empty, check whether checkpoint-storage-account is configured in the configuration file.
	at org.springframework.util.Assert.hasText(Assert.java:289) ~[spring-core-5.3.12.jar:5.3.12]
	at com.azure.spring.integration.eventhub.factory.DefaultEventHubClientFactory.createEventProcessorClientInternal(DefaultEventHubClientFactory.java:89) ~[azure-spring-integration-eventhubs-2.10.0.jar:2.10.0]
	at com.azure.spring.integration.eventhub.factory.DefaultEventHubClientFactory.lambda$createEventProcessorClient$1(DefaultEventHubClientFactory.java:163) ~[azure-spring-integration-eventhubs-2.10.0.jar:2.10.0]
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1705) ~[na:na]
	at com.azure.spring.integration.eventhub.factory.DefaultEventHubClientFactory.createEventProcessorClient(DefaultEventHubClientFactory.java:162) ~[azure-spring-integration-eventhubs-2.10.0.jar:2.10.0]
	at com.azure.spring.integration.eventhub.impl.AbstractEventHubTemplate.createEventProcessorClient(AbstractEventHubTemplate.java:105) ~[azure-spring-integration-eventhubs-2.10.0.jar:2.10.0]
	at com.azure.spring.integration.eventhub.impl.EventHubTemplate.subscribe(EventHubTemplate.java:39) ~[azure-spring-integration-eventhubs-2.10.0.jar:2.10.0]
	at com.azure.spring.integration.core.api.SubscribeByGroupOperation.subscribe(SubscribeByGroupOperation.java:30) ~[azure-spring-integration-core-2.10.0.jar:2.10.0]
	at com.azure.spring.integration.core.AbstractInboundChannelAdapter.doStart(AbstractInboundChannelAdapter.java:43) ~[azure-spring-integration-core-2.10.0.jar:2.10.0]
	at org.springframework.integration.endpoint.AbstractEndpoint.start(AbstractEndpoint.java:157) ~[spring-integration-core-5.5.5.jar:5.5.5]
	at org.springframework.cloud.stream.binder.AbstractMessageChannelBinder.doBindConsumer(AbstractMessageChannelBinder.java:415) ~[spring-cloud-stream-3.1.3.jar:3.1.3]
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 52000652-22d7-ec02-3e24-4a4c97672050
* Version Independent ID: 09d45663-2663-50cc-1388-cb6852860515
* Content: [How to use the Spring Boot Starter for Apache Kafka with Azure Event Hubs](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-cloud-stream-binder-java-app-kafka-azure-event-hub)
* Content Source: [articles/java/spring-framework/configure-spring-cloud-stream-binder-java-app-kafka-azure-event-hub.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/master/articles/java/spring-framework/configure-spring-cloud-stream-binder-java-app-kafka-azure-event-hub.md)
* Service: **event-hubs**
* GitHub Login: @KarlErickson
* Microsoft Alias: **brendm**

**Comment by spelluru** [comment]
@KarlErickson is out of office until new year. I think this one should go through support. Thanks.

**Comment by yiliuTo** [comment]
@jbx1 , could you check your dependencies that if you imported the library of **azure-spring-cloud-starter-eventhubs-kafka** or **azure-spring-cloud-stream-binder-eventhubs**? The library of `azure-spring-integration-eventhubs` shouldn't be imported for the usage of **azure-spring-cloud-starter-eventhubs-kafka**, which is the underlying dependency of **azure-spring-cloud-stream-binder-eventhubs**.

**Comment by jbx1** [comment]
@yiliuTo It has been quite a while now, and I gave up and moved on to use a different product. 

But I was following the document step by step, so none of the dependencies you are mentioning were imported unless they were imported indirectly by `spring-cloud-azure-dependencies` which is explicitly specified in Step 2 of the section _Create a simple Spring Boot application with the Spring Initializr_ of the document (choosing Azure Support adds `spring-cloud-azure-dependencies` to the pom.xml).  

The document then states that these should also be added to the pom.xml file: 

```
<dependency>
  <groupId>com.azure.spring</groupId>
  <artifactId>spring-cloud-azure-starter</artifactId>
  <version>4.0.0</version>
</dependency>
<dependency>
  <groupId>com.azure.spring</groupId>
  <artifactId>spring-cloud-azure-resourcemanager</artifactId>
  <version>4.0.0</version>
</dependency>
<dependency>
  <groupId>org.springframework.cloud</groupId>
  <artifactId>spring-cloud-starter-stream-kafka</artifactId>
  <version>{version}</version><!--Need to be set, for example:3.2.1-->
</dependency>
```

**Comment by yiliuTo** [comment]
Hi @jbx1 , thanks for your following and the information you provided. And now the version and imported libraries in the doc have been updated since we have published the latest version 4.0.0 for the Spring Cloud Azure support, where we redesigned the support for Azure Event Hubs Kafka API as well. Hope you would like to try our new library and the previous exception should not exist. Here are the associated resources you might need: [reference doc](https://microsoft.github.io/spring-cloud-azure/4.0.0/reference/html/index.html#kafka-support) and a [sameple project](https://github.com/Azure-Samples/azure-spring-boot-samples/tree/spring-cloud-azure_v4.0.0/eventhubs/spring-cloud-azure-starter/spring-cloud-azure-sample-eventhubs-kafka).
Besides, to run with spring boot 2.5.x, the spring-cloud-starter-stream-kafka of 3.2.x is not compatible, you can change to 3.1.x.

For any other questions occuring on 4.0.0, you could create an issue in our source code repo: https://github.com/Azure/azure-sdk-for-java/issues

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
Could you please assign this issue to @yiliuTo ?

**Comment by yiliuTo** [comment]
Hi @KarlErickson , I suppose this issue can be closed since there is no response from the customer for long.
