### ISSUE TITLE
The certificates config is still old for 3.14.0 instead of the new 4.3.0

### ISSUE THREAD

**Issue by MarcelTemp** [MicrosoftDocs/azure-dev-docs#853]
The config added to the page does not contain the config for the 4.3.0 version. This still uses the dependency and config of 3.14.0. These do not exist if you want to use it with 4.3.0. Please update, because I cannot get it to work. It almost feels like the code to register a KeyStore is not there. 
The secrets part is working in 4.3.0. It is also documented in detail. This is missing for the certificates part. 

I tried with dependency:

```
<!-- springboot 2.7.2 -->

<dependency>
  <groupId>com.azure.spring</groupId>
  <artifactId>spring-cloud-azure-starter-keyvault-certificates</artifactId><!-- 4.3.0 -->
  <!--artifactId>azure-spring-boot-starter-keyvault-certificates</artifactId--><!-- 3.14.0 -->
</dependency>
```

Config:

```
# azure 4.3.0 libraries
spring.cloud.azure.keyvault:
  certificate:
    endpoint: <key-vault-url>

# azure 3.14.0 libraries (is working)
#azure.keyvault:
#  enabled: true
#  uri: https://dir-d-kv.vault.azure.net/

server:
  port: 443
  ssl:
    enabled: true
    key-alias: <the alias as in the keyvault certificates>
    key-store-type: AzureKeyVault
```

Exception:

```
Caused by: org.springframework.boot.web.server.WebServerException: Could not load key store 'null'
	at org.springframework.boot.web.embedded.jetty.SslServerCustomizer.configureSslKeyStore(SslServerCustomizer.java:228)
	at org.springframework.boot.web.embedded.jetty.SslServerCustomizer.configureSsl(SslServerCustomizer.java:198)
	at org.springframework.boot.web.embedded.jetty.SslServerCustomizer.customize(SslServerCustomizer.java:76)
	at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.customizeSsl(JettyServletWebServerFactory.java:225)
	at org.springframework.boot.web.embedded.jetty.JettyServletWebServerFactory.getWebServer(JettyServletWebServerFactory.java:168)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.createWebServer(ServletWebServerApplicationContext.java:184)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.onRefresh(ServletWebServerApplicationContext.java:162)
	... 16 more
Caused by: java.lang.IllegalArgumentException: Resource location must not be null
	at org.springframework.util.Assert.notNull(Assert.java:201)
	at org.springframework.util.ResourceUtils.getURL(ResourceUtils.java:130)
	at org.springframework.boot.web.embedded.jetty.SslServerCustomizer.configureSslKeyStore(SslServerCustomizer.java:224)
	... 22 more
```

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 7f76c16f-4898-d212-cec3-463f1d5a3912
* Version Independent ID: 10e24fd2-aa87-b300-d4ce-1a4377f4f2fc
* Content: [Tutorial: Secure Spring Boot apps using Azure Key Vault certificates](https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault-certificates)
* Content Source: [articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault-certificates.md](https://github.com/MicrosoftDocs/azure-dev-docs/blob/main/articles/java/spring-framework/configure-spring-boot-starter-java-app-with-azure-key-vault-certificates.md)
* Service: **key-vault**
* GitHub Login: @KarlErickson
* Microsoft Alias: **edburns**

**Comment by saragluna** [comment]
Hi @MarcelTemp, thanks for reaching out. Currently, the 4.x version of Spring Cloud Azure certificates starter doesn't support TLS/mTLS. It only does the auto-configuration of Key Vault certificate clients. We are aware of this feature request, https://github.com/Azure/azure-sdk-for-java/issues/28243, but the implementation would take a redesign and some time, so if you need the TLS support, you still need to use the 3.x version of the certificate starter for now.

**Comment by MarcelTemp** [comment]
@saragluna Thanks for your reply. Maybe mention this in the docs. So users that used this feature in 3.x cannot yet start using 4.x.

**Comment by saragluna** [comment]
@MarcelTemp sorry for the inconvenience. We'll mention it in the doc.

**Comment by chenrujun** [comment]
Hi, @KarlErickson 
Could you please assign this issue to @fangjian0423 ?

**Comment by fangjian0423** [comment]
The tips has been added:

![image](https://user-images.githubusercontent.com/5254035/200239443-45ff3ef9-b44c-487d-9dba-a9a4c3d70402.png)

Thanks for your suggestion @MarcelTemp

**Comment by KarlErickson** [comment]
Doc has been updated. Closing this issue.
